In [ ]:
import sys
sys.path.insert(0, '/storage/agrp/barakma/PileupODD')

In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
from huggingface_hub import HfFileSystem
import polars as pl

fs = HfFileSystem()


with fs.open("datasets/OpenDataDetector/ColliderML-Release-1/data/ttbar_pu0_particles/train-00000-of-00100.parquet", "rb") as f:
    particles = pl.read_parquet(f)

with fs.open("datasets/OpenDataDetector/ColliderML-Release-1/data/ttbar_pu0_calo_hits/train-00000-of-00100.parquet", "rb") as f:
    calo_hits = pl.read_parquet(f)

with fs.open("datasets/OpenDataDetector/ColliderML-Release-1/data/ttbar_pu0_tracks/train-00000-of-00100.parquet", "rb") as f:
    tracks = pl.read_parquet(f)

In [5]:
tracks

shape: (1_000, 9)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ event_id ┆ d0        ┆ z0        ┆ phi       ┆ … ┆ qop       ┆ majority_ ┆ hit_ids   ┆ track_id  │
│ ---      ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ particle_ ┆ ---       ┆ ---       │
│ u32      ┆ list[f32] ┆ list[f32] ┆ list[f32] ┆   ┆ list[f32] ┆ id        ┆ list[list ┆ list[u16] │
│          ┆           ┆           ┆           ┆   ┆           ┆ ---       ┆ [u32]]    ┆           │
│          ┆           ┆           ┆           ┆   ┆           ┆ list[u64] ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0        ┆ [0.032012 ┆ [196.1039 ┆ [-2.82622 ┆ … ┆ [-0.43639 ┆ [299, 88, ┆ [[758,    ┆ [0, 1, …  │
│          ┆ , -0.0252 ┆ 89, 196.1 ┆ 5, -2.705 ┆   ┆ 9,        ┆ … 301]    ┆ 434, …    ┆ 17]       │
│          ┆ 35, …     ┆ 51077, …  ┆ 781, …    ┆   ┆ 0.333322, ┆           ┆ 148],     ┆           │
│          ┆ 0.0357…   ┆ 196…      ┆ 3.060…    ┆   ┆ … 0.7778… ┆           ┆ [1576,    ┆           │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ 157…      ┆           │
│ 1        ┆ [-0.00723 ┆ [106.1146 ┆ [-1.79233 ┆ … ┆ [-0.02572 ┆ [323,     ┆ [[1722,   ┆ [0, 1, …  │
│          ┆ 5, -0.053 ┆ 16, 106.0 ┆ 9, -1.099 ┆   ┆ 7, -0.122 ┆ 137, …    ┆ 1721, …   ┆ 31]       │
│          ┆ 888, …    ┆ 39703, …  ┆ 716, …    ┆   ┆ 754, …    ┆ 371]      ┆ 153],     ┆           │
│          ┆ -0.28…    ┆ 106…      ┆ 2.426…    ┆   ┆ -0.74…    ┆           ┆ [654, 67… ┆           │
│ 2        ┆ [0.001582 ┆ [49.42713 ┆ [-2.18610 ┆ … ┆ [-0.25751 ┆ [377,     ┆ [[1895,   ┆ [0, 1, …  │
│          ┆ ,         ┆ 5, 49.386 ┆ 4, -2.078 ┆   ┆ 9, -0.086 ┆ 423, …    ┆ 699, …    ┆ 38]       │
│          ┆ -0.00831, ┆ 742, …    ┆ 311, …    ┆   ┆ 401, …    ┆ 449]      ┆ 193],     ┆           │
│          ┆ …         ┆ 49.37…    ┆ 3.074…    ┆   ┆ 0.255…    ┆           ┆ [1593,    ┆           │
│          ┆ 0.01824…  ┆           ┆           ┆   ┆           ┆           ┆ 13…       ┆           │
│ 3        ┆ [0.012293 ┆ [60.9883, ┆ [-2.93963 ┆ … ┆ [0.185901 ┆ [344,     ┆ [[3608,   ┆ [0, 1, …  │
│          ┆ , -0.0095 ┆ 61.132366 ┆ 3, -2.722 ┆   ┆ , -0.2829 ┆ 221, …    ┆ 3611, …   ┆ 52]       │
│          ┆ 39, …     ┆ , …       ┆ 635, …    ┆   ┆ 21, …     ┆ 247]      ┆ 419],     ┆           │
│          ┆ 0.0559…   ┆ 61.0850…  ┆ 3.106…    ┆   ┆ 0.3863…   ┆           ┆ [3432, 3… ┆           │
│ 4        ┆ [-0.00191 ┆ [52.50020 ┆ [-2.78375 ┆ … ┆ [-0.28014 ┆ [334,     ┆ [[2372,   ┆ [0, 1, …  │
│          ┆ 8, -0.112 ┆ 2, 52.585 ┆ 8, -2.467 ┆   ┆ 2, -0.704 ┆ 133, …    ┆ 2373, …   ┆ 43]       │
│          ┆ 189, …    ┆ 842, …    ┆ 226, …    ┆   ┆ 174, …    ┆ 523]      ┆ 334],     ┆           │
│          ┆ -0.11…    ┆ 50.39…    ┆ 3.040…    ┆   ┆ -0.09…    ┆           ┆ [2876, 2… ┆           │
│ …        ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 995      ┆ [-0.00533 ┆ [-75.2995 ┆ [-3.09590 ┆ … ┆ [0.231844 ┆ [713,     ┆ [[3068,   ┆ [0, 1, …  │
│          ┆ 9,        ┆ 45, -75.5 ┆ 9,        ┆   ┆ ,         ┆ 731, …    ┆ 3070, …   ┆ 91]       │
│          ┆ 0.178722, ┆ 38338, …  ┆ -2.66912, ┆   ┆ 0.097704, ┆ 743]      ┆ 478],     ┆           │
│          ┆ … 0.0216… ┆ -75…      ┆ … 3.0484… ┆   ┆ …         ┆           ┆ [4935, 4… ┆           │
│          ┆           ┆           ┆           ┆   ┆ -0.0285…  ┆           ┆           ┆           │
│ 996      ┆ [0.027836 ┆ [-1.17195 ┆ [-3.01027 ┆ … ┆ [0.48127, ┆ [767,     ┆ [[4677,   ┆ [0, 1, …  │
│          ┆ ,         ┆ 2, -1.465 ┆ 1, -3.048 ┆   ┆ -0.094376 ┆ 317, …    ┆ 4676, …   ┆ 74]       │
│          ┆ 0.109946, ┆ 703, …    ┆ 716, …    ┆   ┆ , …       ┆ 314]      ┆ 686],     ┆           │
│          ┆ …         ┆ -1.17…    ┆ 3.075…    ┆   ┆ 0.07127…  ┆           ┆ [1986, 2… ┆           │
│          ┆ 0.01127…  ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 997      ┆ [-0.06255 ┆ [86.04416 ┆ [-3.04129 ┆ … ┆ [0.140797 ┆ [647,     ┆ [[3375,   ┆ [0, 1, …  │
│          ┆ 3,        ┆ 7, 85.875 ┆ 2, -3.085 ┆   ┆ , -0.7155 ┆ 619, …    ┆ 3378, …   ┆ 80]       │
│          ┆ 0.072479, ┆ 015, …    ┆ 649, …    ┆   ┆ 54, …     ┆ 420]      ┆ 445],     ┆           │
│          ┆ … -0.027… ┆ 86.25…    ┆ 2.697…    ┆   ┆ 0.1109…   ┆           ┆ [3879, 3… ┆           │
│ 998      ┆ [0.360978 ┆ [60.12985 ┆ [-2.57965 ┆ … ┆ [-0.09335 ┆ [590,     ┆ [[1783,   ┆ [0, 1, …  │
│          ┆ ,         ┆ 6, 55.190 ┆ 4, -2.572 ┆   ┆ 7,        ┆ 518, …    ┆ 1792, …   ┆ 41]       │
│          ┆ 0.251291, ┆ 578, …    ┆ 098, …    ┆   ┆ -0.03177, ┆ 514]      ┆ 327],     ┆           │
│          ┆ …         ┆ 56.40…    ┆ 2.001…    ┆   ┆ … 0.0067… ┆           ┆ [1835, 1… ┆           │
│          ┆ 0.01020…  ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 999      ┆ [-1.05298 ┆ [-23.5689 ┆ [-3.06523 ┆ … ┆ [0.242131 ┆ [759,     ┆ [[4292,   ┆ [0, 1, …  │
│          ┆ 7, -0.090 ┆ 43, -23.1 ┆ 7, -3.114 ┆   ┆ , -0.0591 ┆ 692, …    ┆ 4290, …   ┆ 58]       │
│          ┆ 866, …    ┆ 33175, …  ┆ 643, …    ┆   ┆ 65, …     ┆ 736]      ┆ 267],     ┆           │
│          ┆ 0.132…    ┆ -24…      ┆ 3.117…    ┆   ┆ 0.4237…   ┆           ┆ [3419, 3… ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [7]:
from primary.preprocessing import preprocess_for_model
preprocessed = preprocess_for_model(particles=particles, tracks=tracks, calo_hits=calo_hits, num_of_events=100)

Computing parent existence mask...
Step 1: Building the Static Lookup Table (The Census)...
Step 2: initializing Active Paths for Depositors only...
Converged after 10 iterations on 444447 depositors.
Preparing lineage map...
Converged after 5 iterations.
--- Starting Optimized 3D Clustering (MeanShift, bw=120.0) ---
Data prepared: 100 events. Time: 0.07s
Workload optimized: 100 events merged into 100 tasks.
Largest batch processing first (LPT scheduling).
Aggregating results...
Done. Total time: 27.68s

In [8]:
particles

shape: (1_000, 18)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ event_id ┆ particle_ ┆ pdg_id    ┆ mass      ┆ … ┆ perigee_z ┆ vertex_pr ┆ parent_id ┆ primary   │
│ ---      ┆ id        ┆ ---       ┆ ---       ┆   ┆ 0         ┆ imary     ┆ ---       ┆ ---       │
│ u32      ┆ ---       ┆ list[i64] ┆ list[f32] ┆   ┆ ---       ┆ ---       ┆ list[i64] ┆ list[bool │
│          ┆ list[u64] ┆           ┆           ┆   ┆ list[f32] ┆ list[u16] ┆           ┆ ]         │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0        ┆ [76, 77,  ┆ [213,     ┆ [0.738762 ┆ … ┆ [NaN,     ┆ [1, 1, …  ┆ [9, 9, …  ┆ [true,    │
│          ┆ … 2033]   ┆ -211, …   ┆ ,         ┆   ┆ NaN, …    ┆ 1]        ┆ 2019]     ┆ true, …   │
│          ┆           ┆ 11]       ┆ 0.13957,  ┆   ┆ NaN]      ┆           ┆           ┆ false]    │
│          ┆           ┆           ┆ …         ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ 0.000511… ┆   ┆           ┆           ┆           ┆           │
│ 1        ┆ [10, 11,  ┆ [211,     ┆ [0.13957, ┆ … ┆ [NaN,     ┆ [1, 1, …  ┆ [3, 3, …  ┆ [true,    │
│          ┆ … 2879]   ┆ -211, …   ┆ 0.13957,  ┆   ┆ NaN, …    ┆ 1]        ┆ 80]       ┆ true, …   │
│          ┆           ┆ 22]       ┆ … 0.0]    ┆   ┆ 0.0]      ┆           ┆           ┆ false]    │
│ 2        ┆ [64, 65,  ┆ [-523,    ┆ [5.3252,  ┆ … ┆ [49.38608 ┆ [1, 1, …  ┆ [9, 9, …  ┆ [true,    │
│          ┆ … 3238]   ┆ 111, …    ┆ 0.13498,  ┆   ┆ 9, 49.387 ┆ 1]        ┆ 3236]     ┆ true, …   │
│          ┆           ┆ 11]       ┆ …         ┆   ┆ 272, …    ┆           ┆           ┆ false]    │
│          ┆           ┆           ┆ 0.000511] ┆   ┆ NaN]      ┆           ┆           ┆           │
│ 3        ┆ [43, 44,  ┆ [2212,    ┆ [0.93827, ┆ … ┆ [62.26707 ┆ [1, 1, …  ┆ [8, 8, …  ┆ [true,    │
│          ┆ … 4223]   ┆ 221, …    ┆ 0.54785,  ┆   ┆ 5, 61.456 ┆ 1]        ┆ 136]      ┆ true, …   │
│          ┆           ┆ 22]       ┆ … 0.0]    ┆   ┆ 688, …    ┆           ┆           ┆ false]    │
│          ┆           ┆           ┆           ┆   ┆ 60.89…    ┆           ┆           ┆           │
│ 4        ┆ [113,     ┆ [223,     ┆ [0.780666 ┆ … ┆ [0.0, 52. ┆ [1, 1, …  ┆ [8, 8, …  ┆ [true,    │
│          ┆ 114, …    ┆ 211, …    ┆ ,         ┆   ┆ 045685, … ┆ 1]        ┆ 2385]     ┆ true, …   │
│          ┆ 2391]     ┆ 11]       ┆ 0.13957,  ┆   ┆ NaN]      ┆           ┆           ┆ false]    │
│          ┆           ┆           ┆ …         ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ 0.000511… ┆   ┆           ┆           ┆           ┆           │
│ …        ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 995      ┆ [80, 81,  ┆ [-321,    ┆ [0.49368, ┆ … ┆ [-75.3232 ┆ [1, 1, …  ┆ [9, 9, …  ┆ [true,    │
│          ┆ … 5670]   ┆ 223, …    ┆ 0.793777, ┆   ┆ 42, -75.3 ┆ 1]        ┆ 5661]     ┆ true, …   │
│          ┆           ┆ -11]      ┆ …         ┆   ┆ 22495, …  ┆           ┆           ┆ false]    │
│          ┆           ┆           ┆ 0.000511… ┆   ┆ NaN…      ┆           ┆           ┆           │
│ 996      ┆ [29, 30,  ┆ [-211,    ┆ [0.13957, ┆ … ┆ [-1.22567 ┆ [1, 1, …  ┆ [9, 9, …  ┆ [true,    │
│          ┆ … 6397]   ┆ 111, …    ┆ 0.13498,  ┆   ┆ 4, -1.206 ┆ 1]        ┆ 6389]     ┆ true, …   │
│          ┆           ┆ 2212]     ┆ …         ┆   ┆ 324, …    ┆           ┆           ┆ false]    │
│          ┆           ┆           ┆ 0.938272] ┆   ┆ NaN]      ┆           ┆           ┆           │
│ 997      ┆ [145,     ┆ [221,     ┆ [0.54785, ┆ … ┆ [86.05157 ┆ [1, 1, …  ┆ [8, 8, …  ┆ [true,    │
│          ┆ 146, …    ┆ 111, …    ┆ 0.13498,  ┆   ┆ 5, 86.062 ┆ 1]        ┆ 8072]     ┆ true, …   │
│          ┆ 8076]     ┆ 11]       ┆ …         ┆   ┆ 393, …    ┆           ┆           ┆ false]    │
│          ┆           ┆           ┆ 0.000511] ┆   ┆ NaN]      ┆           ┆           ┆           │
│ 998      ┆ [31, 32,  ┆ [-213,    ┆ [1.211043 ┆ … ┆ [55.95936 ┆ [1, 1, …  ┆ [18, 18,  ┆ [true,    │
│          ┆ … 4038]   ┆ 211, …    ┆ ,         ┆   ┆ 6, NaN, … ┆ 1]        ┆ … 4035]   ┆ true, …   │
│          ┆           ┆ 11]       ┆ 0.13957,  ┆   ┆ 4907.0214 ┆           ┆           ┆ false]    │
│          ┆           ┆           ┆ …         ┆   ┆ 84…       ┆           ┆           ┆           │
│          ┆           ┆           ┆ 0.000511… ┆   ┆           ┆           ┆           ┆           │
│ 999      ┆ [33, 34,  ┆ [-313,    ┆ [0.872462 ┆ … ┆ [-23.5847 ┆ [1, 1, …  ┆ [8, 8, …  ┆ [true,    │
│          ┆ … 6288]   ┆ -211, …   ┆ ,         ┆   ┆ 03, -23.4 ┆ 1]        ┆ 6285]     ┆ true, …   │
│          ┆           ┆ 11]       ┆ 0.13957,  ┆   ┆ 63879, …  ┆           ┆           ┆ false]    │
│          ┆           ┆           ┆ …         ┆   ┆ -58…      ┆           ┆           ┆           │
│          ┆           ┆           ┆ 0.000511… ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [9]:
# write preprocessed data to local disk as parquets
file_path = "/storage/agrp/barakma/PileupODD/data"
for key, df in preprocessed.items():
    df.write_parquet(f"{file_path}/preprocessed_{key}.parquet")

In [10]:
# try to see if i can load one of them
cl=pl.read_parquet(f"{file_path}/preprocessed_calo_clusters.parquet")
cl

shape: (100, 6)
┌──────────┬───────────────┬─────────────────┬─────────────────┬─────────────────┬─────────────────┐
│ event_id ┆ cluster_id    ┆ total_cluster_e ┆ cluster_cx      ┆ cluster_cy      ┆ cluster_cz      │
│ ---      ┆ ---           ┆ nergy           ┆ ---             ┆ ---             ┆ ---             │
│ u32      ┆ list[i32]     ┆ ---             ┆ list[f32]       ┆ list[f32]       ┆ list[f32]       │
│          ┆               ┆ list[f64]       ┆                 ┆                 ┆                 │
╞══════════╪═══════════════╪═════════════════╪═════════════════╪═════════════════╪═════════════════╡
│ 0        ┆ [0, 1, … 330] ┆ [117.038543,    ┆ [82.099648,     ┆ [-1263.230957,  ┆ [3305.375977,   │
│          ┆               ┆ 13.86953, …     ┆ 862.302429, …   ┆ 1032.093506, …  ┆ -290.279144, …  │
│          ┆               ┆ 0.012…          ┆ -292…           ┆ …               ┆ 5…              │
│ 1        ┆ [0, 1, … 414] ┆ [127.071303,    ┆ [-279.106384,   ┆ [-1303.080688,  ┆ [-1781.132812,  │
│          ┆               ┆ 65.037671, …    ┆ 453.047211, …   ┆ -777.688049, …  ┆ -3294.084961,   │
│          ┆               ┆ 0.03…           ┆ -2…             ┆ …               ┆ ……              │
│ 2        ┆ [0, 1, … 593] ┆ [59.975367,     ┆ [-1330.139282,  ┆ [112.237022,    ┆ [330.038788,    │
│          ┆               ┆ 47.772519, …    ┆ -608.895935, …  ┆ -1213.421143, … ┆ -2807.855225, … │
│          ┆               ┆ 0.033…          ┆ …               ┆ 4…              ┆ 8…              │
│ 3        ┆ [0, 1, … 713] ┆ [48.13458,      ┆ [-784.961243,   ┆ [1118.737671,   ┆ [426.975983,    │
│          ┆               ┆ 45.11502, …     ┆ 1231.401367, …  ┆ -535.188843, …  ┆ -327.448303, …  │
│          ┆               ┆ 0.01551…        ┆ -…              ┆ -…              ┆ 36…             │
│ 4        ┆ [0, 1, … 484] ┆ [46.673636,     ┆ [1125.668335,   ┆ [-730.552307,   ┆ [1113.420532,   │
│          ┆               ┆ 14.84895, …     ┆ 707.334534, …   ┆ 1171.266846, …  ┆ 806.041016, …   │
│          ┆               ┆ 0.0246…         ┆ -1…             ┆ 7…              ┆ 69…             │
│ …        ┆ …             ┆ …               ┆ …               ┆ …               ┆ …               │
│ 95       ┆ [0, 1, … 617] ┆ [66.242444,     ┆ [-334.895905,   ┆ [-215.548737,   ┆ [-3305.510254,  │
│          ┆               ┆ 72.488217, …    ┆ 321.225037, …   ┆ -1292.880737, … ┆ 1501.251709, …  │
│          ┆               ┆ 0.781…          ┆ -2…             ┆ …               ┆ …               │
│ 96       ┆ [0, 1, … 840] ┆ [115.692938,    ┆ [-846.895569,   ┆ [-1037.897461,  ┆ [643.532349,    │
│          ┆               ┆ 75.688911, …    ┆ 784.731628, …   ┆ 1089.703979, …  ┆ -762.927063, …  │
│          ┆               ┆ 0.03…           ┆ -2…             ┆ …               ┆ 17…             │
│ 97       ┆ [0, 1, … 991] ┆ [1230.503656,   ┆ [-401.495972,   ┆ [40.472782,     ┆ [-3335.438477,  │
│          ┆               ┆ 494.178099, …   ┆ 688.888123, …   ┆ -416.98941, …   ┆ -3323.664062,   │
│          ┆               ┆ 0.…             ┆ -2…             ┆ -60.…           ┆ ……              │
│ 98       ┆ [0, 1, … 686] ┆ [81.74963,      ┆ [-1183.378174,  ┆ [701.299561,    ┆ [-1299.378418,  │
│          ┆               ┆ 65.835628, …    ┆ -705.381165, …  ┆ -1145.533691, … ┆ 2429.78833, …   │
│          ┆               ┆ 0.1169…         ┆ …               ┆ 7…              ┆ -…              │
│ 99       ┆ [0, 1, … 639] ┆ [273.451562,    ┆ [-525.414429,   ┆ [-174.205292,   ┆ [-3313.025146,  │
│          ┆               ┆ 84.748371, …    ┆ -445.88855, …   ┆ 243.374619, …   ┆ -3334.037109,   │
│          ┆               ┆ 0.01…           ┆ -1…             ┆ -3…             ┆ ……              │
└──────────┴───────────────┴─────────────────┴─────────────────┴─────────────────┴─────────────────┘